/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cpe321_project;

import java.awt.*;
import javax.swing.*;
import javax.swing.text.DefaultCaret;


/**
 *
 * @author david_b2003
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    
    protected mainForm() {

        
        initComponents();
        /*
        GameManager manager = GameManager.getInstance();
         
        manager.initializeGame();
        manager.playGame();
        Hand currentHand = manager.getPlayer().getHand();
        Hand dealerHand = manager.getDealer().getHand();
        DisplayHand(currentHand, userCardsPanel);
        DisplayHand(dealerHand, dealerCardsPanel); */
    }
    public void ClearStatusBar(){
        statusTextArea.setText("");
        DefaultCaret caret = (DefaultCaret)statusTextArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        statusTextArea.revalidate();
    }
    public void AddToStatusBar(String text){
        statusTextArea.append(text + "\n");
        DefaultCaret caret = (DefaultCaret)statusTextArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        statusTextArea.revalidate();
    }
    public void AddToStatusBarNoReturn(String text){
        statusTextArea.append(text);
        DefaultCaret caret = (DefaultCaret)statusTextArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        statusTextArea.revalidate();
    }
    private static final mainForm theInstance = new mainForm();
    public static mainForm getInstance() {
       return theInstance;
        } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        startPanel1 = new cpe321_project.startPanel();
        startButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        backGroundPanel1 = new cpe321_project.backGroundPanel();
        leftDoorButton = new javax.swing.JButton();
        hitButton = new javax.swing.JButton();
        stayButton = new javax.swing.JButton();
        storeDoorButton = new javax.swing.JButton();
        storeDoorButton1 = new javax.swing.JButton();
        userCardsPanel = new javax.swing.JPanel();
        dealerCardsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTextArea = new cpe321_project.TransparentTextArea();
        moneyLabel = new javax.swing.JLabel();
        storePanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(800, 600));
        jLayeredPane1.setLayout(new javax.swing.OverlayLayout(jLayeredPane1));

        startPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        startPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startButton.setOpaque(false);
        startButton.setContentAreaFilled(false);
        startButton.setBorderPainted(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        startPanel1.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 121, 56));

        quitButton.setBorderPainted(false);
        quitButton.setOpaque(false);
        quitButton.setContentAreaFilled(false);
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        startPanel1.add(quitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 214, 123, 56));

        jLayeredPane1.add(startPanel1);

        backGroundPanel1.setBackground(new java.awt.Color(0, 204, 0));
        backGroundPanel1.setAutoscrolls(true);
        backGroundPanel1.setOpaque(false);
        backGroundPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        backGroundPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftDoorButton.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.background"));
        leftDoorButton.setBorderPainted(false);
        leftDoorButton.setContentAreaFilled(false);
        leftDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorButtonActionPerformed(evt);
            }
        });
        backGroundPanel1.add(leftDoorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 110, 155));

        hitButton.setText("Hit");
        hitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitButtonActionPerformed(evt);
            }
        });
        backGroundPanel1.add(hitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 90, 39));

        stayButton.setText("Stay");
        stayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stayButtonActionPerformed(evt);
            }
        });
        backGroundPanel1.add(stayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 90, 39));

        storeDoorButton.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.background"));
        storeDoorButton.setBorderPainted(false);
        storeDoorButton.setContentAreaFilled(false);
        storeDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeDoorButtonActionPerformed(evt);
            }
        });
        backGroundPanel1.add(storeDoorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 119, 156));

        storeDoorButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.background"));
        storeDoorButton1.setBorderPainted(false);
        storeDoorButton1.setContentAreaFilled(false);
        storeDoorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeDoorButton1ActionPerformed(evt);
            }
        });
        backGroundPanel1.add(storeDoorButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 26, 87, 135));

        userCardsPanel.setMinimumSize(new java.awt.Dimension(383, 113));
        userCardsPanel.setOpaque(false);

        javax.swing.GroupLayout userCardsPanelLayout = new javax.swing.GroupLayout(userCardsPanel);
        userCardsPanel.setLayout(userCardsPanelLayout);
        userCardsPanelLayout.setHorizontalGroup(
            userCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        userCardsPanelLayout.setVerticalGroup(
            userCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        backGroundPanel1.add(userCardsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 222, 70));

        dealerCardsPanel.setMinimumSize(new java.awt.Dimension(383, 113));
        dealerCardsPanel.setOpaque(false);

        javax.swing.GroupLayout dealerCardsPanelLayout = new javax.swing.GroupLayout(dealerCardsPanel);
        dealerCardsPanel.setLayout(dealerCardsPanelLayout);
        dealerCardsPanelLayout.setHorizontalGroup(
            dealerCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dealerCardsPanelLayout.setVerticalGroup(
            dealerCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        backGroundPanel1.add(dealerCardsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 222, 70));

        statusTextArea.setEditable(false);
        statusTextArea.setBackground(new java.awt.Color(0, 153, 51));
        statusTextArea.setColumns(20);
        statusTextArea.setLineWrap(true);
        statusTextArea.setRows(5);
        jScrollPane1.setViewportView(statusTextArea);

        backGroundPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 799, 110));

        moneyLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        moneyLabel.setText("$0");
        backGroundPanel1.add(moneyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, -10, 160, 40));

        jLayeredPane1.add(backGroundPanel1);

        storePanel.setMinimumSize(new java.awt.Dimension(800, 600));
        storePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Go Back To Casino");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        storePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 180, 40));

        jLayeredPane1.add(storePanel);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 562));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayHand(Hand currentHand, JPanel thePanel){
        thePanel.removeAll();
        thePanel.repaint();
        thePanel.setLayout(new java.awt.FlowLayout());
        for(Card e: currentHand.getCards())
        {
            JLabel label;
            if(e.getHidden())
                label = new JLabel(" ");
            else
                label = new JLabel("<html>" + e.getFace() + " of" + "<br>" + e.getSuit() + "<html>");
            label.setFont(new Font(label.getFont().getName(), Font.PLAIN, 10));
            
            label.setBorder(new javax.swing.border.LineBorder(Color.BLACK));
            label.setPreferredSize(new Dimension(45, 60));
            label.setBackground(Color.WHITE);
            label.setOpaque(true);
            thePanel.add(label);
        }
        thePanel.revalidate();
        
        //Display Player Score
        GameManager manager = GameManager.getInstance();
        int score = manager.getPlayer().getPoints();
        String str = "$" + Integer.toString(score);
        moneyLabel.setText(str);
     
    }
    private void DiplayAllHands()
    {
        GameManager manager = GameManager.getInstance();
        Hand currentHand = manager.getPlayer().getHand();
        Hand dealerHand = manager.getDealer().getHand();
        DisplayHand(currentHand, userCardsPanel);
        DisplayHand(dealerHand, dealerCardsPanel);
    }
    private void HideAllPanelsExcept(JPanel panel){
        startPanel1.setVisible(false);
        backGroundPanel1.setVisible(false);
        storePanel.setVisible(false);
        panel.setVisible(true);
        jLayeredPane1.moveToFront(panel);
    }
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        GameManager manager = GameManager.getInstance();
         
        manager.initializeGame();
        manager.playGame();
        DiplayAllHands();
        HideAllPanelsExcept(backGroundPanel1);
    }//GEN-LAST:event_startButtonActionPerformed

    private void storeDoorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeDoorButton1ActionPerformed
        // TODO add your handling code here:
        GameManager manager = GameManager.getInstance();
        manager.listenForMove("store");
        HideAllPanelsExcept(storePanel);
    }//GEN-LAST:event_storeDoorButton1ActionPerformed

    private void storeDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeDoorButtonActionPerformed
        // TODO add your handling code here:
        GameManager manager = GameManager.getInstance();
        manager.listenForMove("left");
        DiplayAllHands();
        backGroundPanel1.repaint();
        backGroundPanel1.revalidate();
    }//GEN-LAST:event_storeDoorButtonActionPerformed

    private void stayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stayButtonActionPerformed
        // TODO add your handling code here:
        GameManager manager = GameManager.getInstance();
        manager.listenForMove("stay");
        DiplayAllHands();
        
        //Update Player Score
        //int score = manager.getPlayer().getPoints();
        //String str = "$" + Integer.toString(score);
        //moneyLabel.setText(str);
    }//GEN-LAST:event_stayButtonActionPerformed

    private void hitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitButtonActionPerformed
        // TODO add your handling code here:
        GameManager manager = GameManager.getInstance();
        manager.listenForMove("hit");
        DiplayAllHands();
        
        //Update Player Score
        //int score = manager.getPlayer().getPoints();
        //String str = "$" + Integer.toString(score);
        //moneyLabel.setText(str);

    }//GEN-LAST:event_hitButtonActionPerformed

    private void leftDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDoorButtonActionPerformed
        // TODO add your handling code here:
        GameManager manager = GameManager.getInstance();
        manager.listenForMove("right");
        DiplayAllHands();
        backGroundPanel1.repaint();
        backGroundPanel1.revalidate();

    }//GEN-LAST:event_leftDoorButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GameManager manager = GameManager.getInstance();
        manager.listenForMove("exit");
        DiplayAllHands();
        HideAllPanelsExcept(backGroundPanel1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        HideAllPanelsExcept(startPanel1);
        Object[] options = {"Quit", "Nope"};
        JFrame frame = new JFrame();
        int n = JOptionPane.showOptionDialog(frame, 
                "Are you sure you want to quit",
                "Quitters aren't cool",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
              
        if(n == JOptionPane.YES_OPTION)
            System.exit(0);
        else
        {
            frame.setVisible(false);
            frame.dispose();
        }
    }//GEN-LAST:event_quitButtonActionPerformed
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new mainForm().setVisible(true);
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cpe321_project.backGroundPanel backGroundPanel1;
    private javax.swing.JPanel dealerCardsPanel;
    private javax.swing.JButton hitButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leftDoorButton;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton startButton;
    private cpe321_project.startPanel startPanel1;
    private cpe321_project.TransparentTextArea statusTextArea;
    private javax.swing.JButton stayButton;
    private javax.swing.JButton storeDoorButton;
    private javax.swing.JButton storeDoorButton1;
    private javax.swing.JPanel storePanel;
    private javax.swing.JPanel userCardsPanel;
    // End of variables declaration//GEN-END:variables
}
